### PR TITLE
Use dedicated workflow for page rendering check for historical API docs

### PR DESCRIPTION
**Pull request by Eric-Arellano**
It takes over 3 hours for us to check that every page renders in the app. So, it was too slow to have that check every time we make a change to API docs.

Still, it's a useful check and we can't expect humans to run that check, realistically. So, we keep the check but only run it once a week and when translations are changed.

### CODE REVIEW

**Review by frankharkins — COMMENTED** [review]
Thanks! For the scheduled job, do you want to create an issue or comment if it fails? Otherwise we might miss it.

**Comment by Eric-Arellano** [comment]
Yes, but it's a little more work than I first expected. See https://github.com/Qiskit/documentation/issues/547. I don't think we should block on it.

**Comment by frankharkins** [comment]
Since this only runs once a week, what you think of just making a new issue each time? Then the command should be a one-liner

**Comment by Eric-Arellano** [comment]
> Since this only runs once a week, what you think of just making a new issue each time? Then the command should be a one-liner.
>
> EDIT: To be clear, I don't have a strong opinion on this

I think it'd be good to add, but I'd rather not block on this and it's blocking https://github.com/Qiskit/documentation/pull/624 because the current CI check is so slow.

**Review by frankharkins — APPROVED** [review]

**Pull request merged**
