### PR TITLE
remove comparison file

### PR DESCRIPTION
**Pull request by beckykd**

### CODE REVIEW

**Review by Eric-Arellano — APPROVED** [review]
Thanks!

**Review by Eric-Arellano — CHANGES_REQUESTED** [review]
Oh wait, you also need to update `migration-guides/index.mdx`

**Comment by abbycross** [comment]
> Oh wait, you also need to update `migration-guides/index.mdx`

The index page will just link to two migration guides -- is that correct?

**Review by Eric-Arellano — APPROVED** [review]
Yep. Thanks!

**Comment by Eric-Arellano** [comment]
@beckykd is this good to merge or you want more review?

**Pull request merged**
