### PR TITLE
chore: Update contact link

### PR DESCRIPTION
**Pull request by ThomasMerkh**
This PR updates the contact link for one of Q-CTRL's docs notebooks.

### CODE REVIEW

**Review by Eric-Arellano — APPROVED** [review]
Thanks! Looks good. Can you please sign the Contributor License Agreement? See the auto-generated comment on this PR.

**Comment by ThomasMerkh** [comment]
> Thanks! Looks good. Can you please sign the Contributor License Agreement? See the auto-generated comment on this PR.

No problem, completed

**Comment by Eric-Arellano** [comment]
> No problem, completed

Thank you! It looks like it's still not linking up correctly because of the below warning. The bot is using the email address from your commits, which you can see with `git log`.

> Tom Merkh seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

Two ways to fix this:

1. Add your Q-CTRL email to your personal GitHub.
2. Rewrite the commits to use another email address associated with your GitHub. You can do this at a repo-level by following https://stackoverflow.com/a/37805844

**Comment by ThomasMerkh** [comment]
Thanks @Eric-Arellano all this time I didn't realize my Q-CTRL email wasn't verified on my account. It should be now, can you re-trigger the bot to check now (option 1)?

**Comment by Eric-Arellano** [comment]
That worked. Thanks! I'll open a PR to deploy your change this afternoon.

**Pull request merged**
