### PR TITLE
rename repitition -> repetition

### PR DESCRIPTION
**Pull request by kevinsung**

### CODE REVIEW

**Comment by abbycross** [comment]
Thanks Kevin, that was bugging me :-)

**Review by abbycross — APPROVED** [review]

**Review by Eric-Arellano — APPROVED** [review]
Thanks. You also need to update

https://github.com/Qiskit/documentation/blob/3e04681a40cdca8797cac114bd10d34ce18b59d1/tutorials/learning-api.conf.yaml#L23

https://github.com/Qiskit/documentation/blob/3e04681a40cdca8797cac114bd10d34ce18b59d1/scripts/nb-tester/notebooks.toml#L13

Would be good to grep for if there are any other places as well

**Comment by frankharkins** [comment]
Ooops, thanks for fixing!

**Comment by kevinsung** [comment]
> Thanks. You also need to update
> 
> https://github.com/Qiskit/documentation/blob/3e04681a40cdca8797cac114bd10d34ce18b59d1/tutorials/learning-api.conf.yaml#L23
> 
> https://github.com/Qiskit/documentation/blob/3e04681a40cdca8797cac114bd10d34ce18b59d1/scripts/nb-tester/notebooks.toml#L13
> 
> Would be good to grep for if there are any other places as well

Done, those were the only places.

**Pull request merged**
