### PR TITLE
Update hello-world.ipynb

### PR DESCRIPTION
**Pull request by jaygambetta**
I would rather use something like this “little endian” as strictly endianness is a description of byte-ordering and since qiskit doesn’t have the ability to address bytes in memory, endianness does not apply;

### CODE REVIEW

**Comment by abbycross** [comment]
Just FYI -- [related work](https://github.com/Qiskit/documentation/pull/207) going on in a new file to be added.

**Comment by jaygambetta** [comment]
ok but we do need to stop calling it endian as it really is not.

**Comment by abbycross** [comment]
Yep we are removing that terminology. Also, you broke the notebook 😆 so I'm going to revert your changes and reapply them, so don't worry if you see reverted changes in the history

**Comment by abbycross** [comment]
@jaygambetta our preview is temporarily broken, so here's a screenshot of what I did offline -- did I get all the latex math formatting correct?
Screenshot 2023-10-26 at 9 23 40 AM

**Comment by jaygambetta** [comment]
ok do what you need and what your posted looked good.

**Review by abbycross — APPROVED** [review]

**Pull request merged**
