### PR TITLE
Reconfigure cspell to use dictionaries

### LINKED ISSUE #827: Better configure cspell by using dictionaries
See https://github.ibm.com/IBM-Q-Software/iqp-channel-docs/pull/1131 for inspiration.

When applying this change, see if it would have caught the problems we missed in https://github.com/Qiskit/documentation/pull/872#issuecomment-1960165963.

### PR DESCRIPTION
**Pull request by kaelynj**
Closes #827

### CODE REVIEW

**Comment by Eric-Arellano** [comment]
Thanks @kaelynj! Try merging `main` and I'm wondering if it will work thanks to Abby C's PR that was just merged. Otherwise, it'd be good to have it be a dedicated PR as a precursor.

**Comment by Eric-Arellano** [comment]
Oh, @kaelynj the issue is that it's checking the docs under `api/{qiskit,qiskit-ibm-provider,qiskit-ibm-runtime}`. Those should be ignored.

**Comment by kaelynj** [comment]
> Oh, @kaelynj the issue is that it's checking the docs under `api/{qiskit,qiskit-ibm-provider,qiskit-ibm-runtime}`. Those should be ignored.

Should be fixed now!

**Review by Eric-Arellano — APPROVED** [review]
🚀 Thanks for updating the README also. Looks great :)

**Pull request merged**
