### PR TITLE
Qiskit addons aqc pages

### LINKED ISSUE #2289: [ NEW GUIDE ] AQC intro
This guide should cover:

    overview of AQC-Tensor package
    pip install instructions (and any specific package installation constraints)

Existing docs for reference:

    aqc explanatory material
    aqc installation page

### PR DESCRIPTION
**Pull request by kaelynj**
Closes #2289 and #2290

### CODE REVIEW

**Comment by jenglick** [comment]
@kaelynj thank you! here are some review comments:

Overview page: https://qiskit.github.io/documentation/pr-2291/guides/qiskit-addons-aqc

- [ ] Title: "(AQC)" --> "(AQC-Tensor)"

- [ ] first paragraph: "The Approximate quantum compilation with tensor networks (AQC) Qiskit addon enables user to compile ...": "(AQC)" --> "(AQC-Tensor)" and "user" --> "users"

- [ ] first paragraph: "It's primary utility is in circuits which simulate time evolution": "It's" --> "Its"

- [ ] bullet list at top: can we copy verbatim how this is described in the original doc https://qiskit.github.io/qiskit-addon-aqc-tensor/

- [ ] install section: "There are two ways to install the AQC package" --> "There are two ways to install the AQC-Tensor package" and elsewhere

- [ ] install section: add link to the package's github repo somewhere https://github.com/Qiskit/qiskit-addon-aqc-tensor

- [ ] add a next steps section at the end linking to the "getting started" page


Getting started page: https://qiskit.github.io/documentation/pr-2291/guides/qiskit-addons-aqc-get-started

- [ ] "In this page demonstrates a simple working example to get started with AQC-Tensor." --> "This guide demonstrates a simple working example to get started with AQC-Tensor."

- [ ] " In this example, you will take a Trotter circuit which simulates the evolution of a transverse field Ising model and use the AQC method to reduce the resulting circuit depth" -- "AQC" --> "AQC-Tensor"

- [ ] section title "Split the circuit into two pieces for classical and quantum execution" --> "Split the time evolution into two pieces for classical and quantum execution"

- [ ] first bullet of that same section: "An initial portion which is simulable using matrix product states (MPS). This will be what is 'compiled' using AQC." --> "An initial portion which is simulable using matrix product states (MPS). This will be what is 'compiled' using AQC-Tensor."

- [ ] same section: "From here we will next generate two circuits, one which will be compressed using AQC and one which will be executed on a QPU." --> "From here we will generate two circuits, one that will be compressed using AQC-Tensor and one that will be executed on a QPU."

- [ ]  same section: "This is the circuit we would have executed has we not used the AQC technique. " --> "This is the circuit we would have executed had we not used the AQC-Tensor technique. "

- [ ] "Next we will generate the circuit which we will generate the ansatz to optimize" --> "Next we will generate the ansatz we will optimize"

**Comment by jenglick** [comment]
@kaelynj The tutorial for AQC in Learning Platform just dropped -- would you be able to add a link to this in the "next steps" section of the getting started page?


https://learning.quantum.ibm.com/tutorial/improved-trotterized-time-evolution-with-approximate-quantum-compilation

**Comment by kaelynj** [comment]
> @kaelynj The tutorial for AQC in Learning Platform just dropped -- would you be able to add a link to this in the "next steps" section of the getting started page?
> 
> https://learning.quantum.ibm.com/tutorial/improved-trotterized-time-evolution-with-approximate-quantum-compilation

Added both this and the OBP tutorial you linked in #2248 (snuck it in here so I didn't have to open another pr for time)

**Review by javabster — APPROVED** [review]
LGTM 🚀

**Review by garrison — APPROVED** [review]
This is great, thank you!

**Pull request merged**
