### PR TITLE
Refactor Krylov tutorial

### PR DESCRIPTION
**Pull request by frankharkins**
This tutorial was originally created in IBM-Quantum-Technical-Enablement/quantum-enablement#11. Part of #1166.

### CODE REVIEW

**Comment by Eric-Arellano** [comment]
Maybe we need a blocklist mechanism for notebooks that completely fail? It'd be best to not try to fix the notebook in this PR, but we also don't want CI to be red.

**Comment by frankharkins** [comment]
I think @abbycross will be working on this branch, so we can fix it in this PR

**Comment by abbycross** [comment]
Hi @miamico! I've gone through to do voice/style edits on this tutorial, and am trying to run the notebook. The code throws an error in Step 3 - can you see what's going on?

**Comment by Eric-Arellano** [comment]
> Hi @miamico! I've gone through to do voice/style edits on this tutorial, and am trying to run the notebook. The code throws an error in Step 3 - can you see what's going on?

Is it that the notebook is using 11 qubits? We're trying to run this notebook with our 5-qubit simulator in CI, but if it requires 11 qubits, that won't work. If this notebook can't be rewritten to work with the 5-qubit simulator, then we need to update `notebooks.toml` to move it from `notebooks_that_submit_jobs` to instead `notebooks_no_mock`. It's desirable to allow us to mock it if possible so that we get more CI validation.

**Comment by miamico** [comment]
I'm working on a version of this notebook that will be using the hardware at utility scale. I'd hold off any further work on this version based on the simulator

**Comment by abbycross** [comment]
> I'm working on a version of this notebook that will be using the hardware at utility scale. I'd hold off any further work on this version based on the simulator

@miamico ok thanks!!

**Comment by frankharkins** [comment]
This is continued in inner-source.

**Pull request closed without merging**
