### PR TITLE
Transpiling against custom backends

### LINKED ISSUE #105: [ NEW PAGE ] Example workflow of transpiling a quantum simulation model for a heterogeneous gate set
## What the new page should cover:
TBD, also needs a shorter title

## SME collaborators (involve for planning and review):
Ali Javadi, Mat Treinish

## Existing resources to build upon

### PR DESCRIPTION
**Pull request by kaelynj**
Closes #105 

This is currently a draft of the new page.  I'll keep making edits and leave the PR here for folks to add their own comments/suggestions.

### CODE REVIEW

**Comment by kaelynj** [comment]
The draft is now ready to look over!

**Comment by kaelynj** [comment]
@Eric-Arellano looks like CI is failing because the `graphviz` library is not included.  Is it fine to include in the `requirements.txt` of nbtester?

**Comment by Eric-Arellano** [comment]
Add it here

https://github.com/Qiskit/documentation/blob/edf17cb6eb6860ae28bbc9b914ca7fa43d7bb110/.github/workflows/notebook-test.yml#L42-L47

**Comment by abbycross** [comment]
@kaelynj under the section about Creating a custom backend, it says the basis gates will be CZ and CX, but it looks like it's pointing to ECR API docs; should CX be ECR?

**Comment by abbycross** [comment]
I checked in with @beckykd about an accessibility situation - specifically, the output called "Fake LOCC backend" has red and grey arrows, and there is no other way to distinguish between the two arrow types if someone is, for example, colorblind. I especially noticed it because the two colors are called out in the text below the output image. I'm sharing here Becky's idea to possibly change the line thickness or shape for one of the colors, to distinguish the two types - would that be possible?

**Comment by kaelynj** [comment]
> I checked in with @beckykd about an accessibility situation - specifically, the output called "Fake LOCC backend" has red and grey arrows, and there is no other way to distinguish between the two arrow types if someone is, for example, colorblind. I especially noticed it because the two colors are called out in the text below the output image. I'm sharing here Becky's idea to possibly change the line thickness or shape for one of the colors, to distinguish the two types - would that be possible?

Unfortunately no, the api only exposes parameters to change the line widths for the whole iage: https://docs.quantum.ibm.com/api/qiskit/qiskit.visualization.plot_gate_map.  Would messing with the opacity work at all?

**Comment by beckykd** [comment]
> > I checked in with @beckykd about an accessibility situation - specifically, the output called "Fake LOCC backend" has red and grey arrows, and there is no other way to distinguish between the two arrow types if someone is, for example, colorblind. I especially noticed it because the two colors are called out in the text below the output image. I'm sharing here Becky's idea to possibly change the line thickness or shape for one of the colors, to distinguish the two types - would that be possible?
> 
> Unfortunately no, the api only exposes parameters to change the line widths for the whole iage: https://docs.quantum.ibm.com/api/qiskit/qiskit.visualization.plot_gate_map. Would messing with the opacity work at all?
> 
> Alternatively I could shout out the qubit indices the lines are connecting to instead of the colors themselves.

I have a couple of thoughts 
1 - Could you do black and grey for better contrast?  I send this image to my extremely color blind friend who says "he can find the two red arrows if he has time and is told, but they don't stand out.  They are hard to see but not impossible"

2 - In addition, shouting out the qubit indices would be great.

Thanks!

**Comment by kaelynj** [comment]
> I have a couple of thoughts 1 - Could you do black and grey for better contrast? I send this image to my extremely color blind friend who says "he can find the two red arrows if he has time and is told, but they don't stand out. They are hard to see but not impossible"
> 
> 2 - In addition, shouting out the qubit indices would be great.
> 
> Thanks!

Done!  Hopefully the figure along with the caption is more accessible now.

**Pull request merged**
